/////////////////////////////////////////////////////////////////////////////
// Name:        filelisttool.h
// Purpose:     
// Author:      RAGO
// Modified by: 
// Created:     Fri  4 Apr 10:50:54 2014
// RCS-ID:      
// Copyright:   (C) 2014 crumbssoftware.com
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Fri 4 Apr 10:50:54 2014

#ifndef _FILELISTTOOL_H_
#define _FILELISTTOOL_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
////@end includes
#include <wx/filepicker.h>

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxDirPickerCtrl ;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_CVFILELISTTOOL 10033
#define ID_FILELISTTOOL_DIRPICKER 10034
#define ID_FILELISTTOOL_TEXT_EXTENSION 10035
#define ID_FILELISTTOOL_TEXT_PREFIX 10036
#define SYMBOL_CVFILELISTTOOL_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_CVFILELISTTOOL_TITLE _("File List Tool")
#define SYMBOL_CVFILELISTTOOL_IDNAME ID_CVFILELISTTOOL
#define SYMBOL_CVFILELISTTOOL_SIZE wxSize(400, 300)
#define SYMBOL_CVFILELISTTOOL_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * CVFileListTool class declaration
 */

class CVFileListTool: public wxDialog
{    
    DECLARE_CLASS( CVFileListTool )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CVFileListTool();
    CVFileListTool( wxWindow* parent, wxWindowID id = SYMBOL_CVFILELISTTOOL_IDNAME, const wxString& caption = SYMBOL_CVFILELISTTOOL_TITLE, const wxPoint& pos = SYMBOL_CVFILELISTTOOL_POSITION, const wxSize& size = SYMBOL_CVFILELISTTOOL_SIZE, long style = SYMBOL_CVFILELISTTOOL_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CVFILELISTTOOL_IDNAME, const wxString& caption = SYMBOL_CVFILELISTTOOL_TITLE, const wxPoint& pos = SYMBOL_CVFILELISTTOOL_POSITION, const wxSize& size = SYMBOL_CVFILELISTTOOL_SIZE, long style = SYMBOL_CVFILELISTTOOL_STYLE );

    /// Destructor
    ~CVFileListTool();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CVFileListTool event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_CLOSE
    void OnCloseClick( wxCommandEvent& event );

////@end CVFileListTool event handler declarations

////@begin CVFileListTool member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CVFileListTool member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin CVFileListTool member variables
    wxDirPickerCtrl * m_dirPicker;
    wxTextCtrl* m_textExtension;
    wxTextCtrl* m_textPrefix;
////@end CVFileListTool member variables
    
    /////////////////////////////////
    //// UNMANAGED SECTION
    /////////////////////////////////
    
    void vSetPath(wxString sPath);
    
    wxString sGetPath();
    wxString sGetExtension();
    wxString sGetPrefix();
    
    
    
    /////////////////////////////////
    //// END OF UNMANAGED SECTION
    /////////////////////////////////
};


#endif
    // _FILELISTTOOL_H_
